name: JuiceShop DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-sbom:
    runs-on: ubuntu-latest
    outputs:
      sbom-path: ${{ steps.generate-sbom.outputs.sbom-file }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t juiceshop .

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        id: generate-sbom
        run: |
          syft juiceshop -o json > sbom.json
          echo "::set-output name=sbom-file::sbom.json"

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  semgrep-scan:
    needs: build-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Semgrep via pip
        run: pip3 install semgrep
        # no need for curl|sh, pip3 works out of the box on ubuntu-latest

      - name: Run Semgrep SaaS-security Scan
        run: |
          semgrep --config 'auto' --sarif -o semgrep-results.sarif .

      - name: Upload Semgrep SARIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.sarif
