name: JuiceShop DevSecOps Pipeline

on:
  push:
    branches:
      - master
jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t juiceshop .

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM with Syft
      run: syft juiceshop -o json > sbom.json
    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.json


    - name: Install Semgrep
      run: |
        curl -sSfL https://semgrep.dev/install | sh

    - name: Run Semgrep scan for SaaS security
      run: semgrep --config='auto' --strict --error 'saas-security' --json -o semgrep-results.json .

    - name: Upload Semgrep Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-results
        path: semgrep-results.json

